### ISSUE TITLE
Consider using the go-ego/gse package for text segmentation

### ISSUE THREAD

**Issue by waybackarchiver** [zoomio/tagify#12]
Hi,

Thanks to @smeshkov for developing tagify, which can help us extract text as tags very well. However, one limitation at the moment is that its Chinese text segmentation is poor.

It appears that the text segmentation with the [go-ego/gse](https://github.com/go-ego/gse) package could provide enhancement, and it can be used here?

**Comment by smeshkov** [comment]
hey @waybackarchiver thanks for reaching out, I'll have a look and will let you know

**Comment by smeshkov** [comment]
hey @waybackarchiver, following up on the issue, hence I'm not familiar in the Chinese language, could you provide some examples of input in Chinese which produce poor results and what would be an expected outputs instead. 

It will help me to understand the problem better. Thanks.

**Comment by waybackarchiver** [comment]
@smeshkov thank you for your reply, here are some poor results from the [tagify](https://www.zoomio.org/tagify) with red underscroe, which are not segmentation to a word.

source: <https://zhuanlan.zhihu.com/p/22637948>

> ![image](https://user-images.githubusercontent.com/66856220/164878640-bc799888-0ed7-459c-b665-655855eee83e.png)

source: [https://telegra.ph/我们是小小小小小的代价--新世界-04-20-3](https://telegra.ph/%E6%88%91%E4%BB%AC%E6%98%AF%E5%B0%8F%E5%B0%8F%E5%B0%8F%E5%B0%8F%E5%B0%8F%E7%9A%84%E4%BB%A3%E4%BB%B7--%E6%96%B0%E4%B8%96%E7%95%8C-04-20-3)

> ![image](https://user-images.githubusercontent.com/66856220/164878784-376ed213-26d1-4dda-9683-775764ab79f1.png)

source: <https://ipfs.io/ipfs/bafybeiaozidubdewtpkvdb3jflgi2632iqwmqkqyqijn5nees4qtnal5ci>

> ![image](https://user-images.githubusercontent.com/66856220/164878850-757eca1f-a6ef-4b53-a0da-3ddc5cb57498.png)

**Comment by smeshkov** [comment]
Thank you @waybackarchiver any chance you could send me the output as a text instead of an image?

**Comment by waybackarchiver** [comment]
> Thank you @waybackarchiver any chance you could send me the output as a text instead of an image?

Updated https://github.com/zoomio/tagify/issues/12#issuecomment-1107366773

**Comment by waybackarchiver** [comment]
@smeshkov If more information is required, I will gratefully provide all.

**Comment by smeshkov** [comment]
hey @waybackarchiver , I apologise for a delay, been busy with other stuff. I've just released version 0.59.0, which is using [go-ego/gse](https://github.com/go-ego/gse) for Chinese and Japanese languages. Please let me know if it works for you as expected.

**Comment by waybackarchiver** [comment]
@smeshkov Thank you for your hard work!

I'll try out the new segmentation logic and report back.
