### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by sergeylukin** [zoomio/tagify#3]
Hi,

First of all, very impressive project. I love the idea. It works great. What is required to make it work with other languages rather than English?

**Comment by smeshkov** [comment]
Hey, thanks, appreciate it!

I've just added support for the Russian words and released it under the tag 0.32.0, you can checkout the diff [here](https://github.com/zoomio/tagify/commit/bc86d358920bee711eb45fef692ca705a07d1334).

In a nutshell, it just requires two things:

- add support for the stopwords - https://github.com/zoomio/stopwords;
- update regex lists with extra letters (specific to the language) [here](https://github.com/zoomio/tagify/blob/master/processor/processor.go#L13-L16).

Does it make sense? Are you planning to add some language? Which language? Maybe I can help. Let me know if you'd like to know more.

**Comment by sergeylukin** [comment]
That's awesome. I've looked into stopwords commit with Russian and it makes sense. I needed Russian btw, so you just made my day :) And it works great!

I will try adding support for Hebrew myself, that would be interesting as it's a right to left language, with unicode chars.

**Comment by smeshkov** [comment]
Sounds great! Lemme know how you go and if you need help.

Also do you mind me asking about how did you Tagify and how you planning to use it? I'd really value your answers, it help me to understand more what to work on and what to prioritize.

**Comment by sergeylukin** [comment]
Well, I tried it with a few blog posts from my website I've launched recently: https://yay.tips I'm planning to use it on the back-end to automatically suggest tags before posting, that would be a huuuuge improvemet for content editors. And although I can think of some other tags automated suggestions (like tags suggestions based on category field or based on specific words found in the title, etc.), they are more like something that can be implemented in a separate library side by side with Tagify and not something that Tagify should implement, maybe, not sure haha. Anyways, great progress so far. Keep up the great work @smeshkov !

**Comment by smeshkov** [comment]
Nice, thanks @sergeylukin ! Suggesting tags before posting - great idea. I have plans to add POS tagging capabilities and categorization, but first I'd like to bring extensibility into the Tagify, so it can be enhanced with plugins. By the way have you seen [TagifyJS](https://github.com/zoomio/tagifyjs)? It can be pluggedin onto any website to generate tags for the pages, I've put together a manual here - [zoomio.org/blog/post/how_to_tagify-5765616870883328](https://zoomio.org/blog/post/how_to_tagify-5765616870883328). What do you think?

**Comment by smeshkov** [comment]
Added support for Chinese, Hindi, Spanish, Arabic, Japanese, German, Hebrew, French and Korean languages in release v0.42.0 - https://github.com/zoomio/tagify/releases/tag/v0.42.1
