### ISSUE TITLE
Linux install fail

### ISSUE THREAD

**Issue by tluyben** [zoomio/tagify#5]
After running the linux install line, I get; 

bash: ../bin/tagify: cannot execute binary file: Exec format error

Running on: 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tluyben** [comment]
https://github.com/zoomio/tagify/releases/download/v0.42.1/tagify_linux_v0.42.1

this one does work, so I guess it takes the wrong version using the installer?

**Comment by smeshkov** [comment]
The problem is in the release. CI just didn't happen to generate the binaries. I'm using Travis CI, but I've had quite a few issues with it already. So I'm going to transition onto something more reliable in the next few days and create new release. Will post update in this issue once it is ready.

**Comment by smeshkov** [comment]
Fixed, here is the link to the latest release https://github.com/zoomio/tagify/releases/tag/v0.45.0
